services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senhaSecreta123
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
