services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - private_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # runs once
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app:
    build: .
    container_name: app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public_network
      - private_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:${APP_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:1.24-alpine
    container_name: engine-x
    ports:
      - 8080:80
      # - 50443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
    networks:
      - public_network

networks:
  public_network:
  private_network:
    internal: true

volumes:
  postgres_data:
