services:
  db:
    image: postgres:18
    container_name: postgres_db
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      TZ: ${TZ}
      PGTZ: ${PGTZ}
    networks:
      - private_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    environment:
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public_network
      - private_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  #two networks for security
  public_network:
    name: nginx-app
    driver: brigde
    ipam:
      config:
        -subnet: 172.20.0.0/24
  private_network:
    name: app-db
    driver: bridge
    internal: true
    ipam:
      config:
        -subnet: 172.21.0.0/24
